# Site settings
title: Read The Docs # site title
description: >- # site description
  Dia menulis dalam bahasa Indonesia tentang teknologi web dan pengalaman sebagai jurnal
  untuk dokumentasi tentang apa yang dia pelajari, lihat dia <a href="https://instagram.com/kelinci7i8" target="_blank" rel="noopener">@instagram</a>.
lang: en-US # default lang
timezone: Asia/Jakarta # set your timezone
image: assets/img/icon.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/bayjdm/klise # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Afri # author name
  bio: >- # tell to the world
    Software Engineering Student, Computer Geek, Amateur Programmer.
  username: afri # general username
  github: africode7 # github username
  twitter: # # twitter username
  facebook: # # facebook username
  instagram: kelinci7i8 # instagram username
  email: blockchainafri7@gmail.com # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://rtd.codegeek.my.id/" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 10

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
